# Generated by Django 6.0.7 on 2026-08-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(default='₹', max_length=5, verbose_name='Currency Symbol'),
        ),
    ]
